/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Container;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Point;
import java.awt.Rectangle;
import javax.swing.Icon;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.Scrollable;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import org.scilab.forge.jlatexmath.ParseException;
import org.scilab.forge.jlatexmath.TeXConstants;
import org.scilab.forge.jlatexmath.TeXFormula;

/**
 *
 * @author Sergio
 */
public class VentanaLatex extends javax.swing.JFrame {

    String textoLatex;
    private LatexView latexPanel;

    /**
     * Creates new form VentanaLatex
     *
     * @param textoLatex
     */
    public VentanaLatex(String textoLatex) {
        initComponents();
        this.textoLatex = textoLatex;
        jTextArea1.setText(textoLatex);

        latexPanel = new LatexView();
        latexPanel.add(jLabel1);
        jScrollPane2.setViewportView(latexPanel);

        jScrollPane2.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        jScrollPane2.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);

        jLabel1.setHorizontalAlignment(SwingConstants.LEFT);
        jLabel1.setVerticalAlignment(SwingConstants.TOP);

        // Reemplaza el GroupLayout por BorderLayout
        getContentPane().removeAll();
        getContentPane().setLayout(new java.awt.BorderLayout());

        javax.swing.JPanel center = new javax.swing.JPanel(new java.awt.GridLayout(1, 2, 18, 0));
        center.add(jScrollPane1);
        center.add(jScrollPane2);

        getContentPane().add(center, java.awt.BorderLayout.CENTER);

        // IMPORTANTE: para que el botón no ocupe todo el ancho
        javax.swing.JPanel south = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER));
        south.add(jButton1);
        getContentPane().add(south, java.awt.BorderLayout.SOUTH);

        // Genera el icono ANTES de pack()
        try {
            generateLatex();
        } catch (ParseException ex) {
            jLabel1.setIcon(null);
            jLabel1.setText("LaTeX inválido");
        }

        jScrollPane2.setBorder(null);
        jScrollPane2.getViewport().setBorder(null);
        latexPanel.setBorder(null);
        jLabel1.setBorder(null);

        setTitle("Visor LaTeX");

        pack();                 // AHORA sí: ya conoce tamaños reales
        setLocationRelativeTo(null);
        setVisible(true);
        setMinimumSize(new Dimension(800, 500));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("jLabel1");
        jScrollPane2.setViewportView(jLabel1);

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(416, 416, 416)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        textoLatex = jTextArea1.getText();
        try {
            generateLatex();
        } catch (ParseException ex) {
            jLabel1.setIcon(null);
            jLabel1.setText("LaTeX inválido");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void generateLatex() throws ParseException {
        TeXFormula formula = new TeXFormula(textoLatex);
        Icon icon = formula.createTeXIcon(TeXConstants.STYLE_DISPLAY, 24);

        jLabel1.setIcon(icon);
        jLabel1.setText(null);

        jLabel1.setPreferredSize(new java.awt.Dimension(icon.getIconWidth(), icon.getIconHeight()));

        // fuerza recomputo del scrollpane correctamente
        latexPanel.revalidate();
        latexPanel.repaint();

        jScrollPane2.getViewport().revalidate();
        jScrollPane2.getViewport().repaint();

        jScrollPane2.getViewport().setViewPosition(new Point(0, 0));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    private static class LatexView extends JPanel implements Scrollable {

        LatexView() {
            super(new FlowLayout(FlowLayout.LEFT, 0, 0));
        }

        @Override
        public Dimension getPreferredScrollableViewportSize() {
            return getPreferredSize();
        }

        @Override
        public int getScrollableUnitIncrement(Rectangle r, int o, int d) {
            return 16;
        }

        @Override
        public int getScrollableBlockIncrement(Rectangle r, int o, int d) {
            return 64;
        }

        // CLAVE: que NO se ajuste al viewport
        @Override
        public boolean getScrollableTracksViewportWidth() {
            return false;
        }

        @Override
        public boolean getScrollableTracksViewportHeight() {
            return false;
        }
    }
}
